### ISSUE TITLE
No input but does show up in windows

### ISSUE THREAD

**Issue by QuentinWehkamp** [DavidPagels/retro-pico-switch#11]
I can not for the life of me figure out why it is not working. it shows on windows as a controller but i cant get any input from it.

I have loaded it with the latest release of the usb.uf2 because i want to use it wired.
I have connected data -> gp18, 3.3v -> 3.3v, gnd -> gnd and a 1k resistor between gp18 and 3.3V. (i didnt wire up rumble because i dont want it)
I have tested continuity from the gamecube controller to the pins and that seems to work. 
I have measured the resistor to see if that was correct, it was.

I've been trying to build this ever since it was posted and i keep coming back to it but i can not figure out what i am doing wrong.

**Comment by DavidPagels** [comment]
Sorry to hear it hasn't been working. Please post pictures of your current setup. Off hand, I'm not sure why it wouldn't be working unless maybe the two ground pins on the gamecube controller aren't internally connected and you're grounding the rumble ground instead of the data 3.3v ground.

**Comment by RyanMac84** [comment]
I have the same issue using the Rumble Support release, if I use the Initial release, it works fine 🤷‍♂️

**Comment by DavidPagels** [comment]
Same request as I had for the OP - Please post pictures of your current setup.

**Comment by DavidPagels** [comment]
Whoops, didn't mean to close

**Comment by RyanMac84** [comment]
Here you go... https://ibb.co/52nSpRT

Please let me know if you need anything else.

**Comment by Sakitoshi** [comment]
@RyanMac84 assuming red is connected to 3v3, black to ground and white to data in the controller, looks good.
as the adapter mimics a switch pro controller you need software for a pc to interpret it correctly. i've been using [this version of betterjoy](https://github.com/d3xMachina/BetterJoy/releases/tag/v8.0) that works on win 11 without issues and is updated to use hidhide instead of the outdated hidguardian, just make sure to change the "NonOriginalController" option to "defaultcalibration" or the stick and c-buttons may not work, alternatively you can just tick "AllowCalibration" for the same effect.
steam also can detect and use the controller if you have steam input enabled for switch controllers.

**Comment by RyanMac84** [comment]
Thanks, with the VigemBus drivers and BetterJoy setup, the controller now shows as a Xinput Standard Gamepad in Windows 11 Game Controllers, however, even though it looks like the 'Test' is now working, the analogue stick does not do anything and the 'Z' button on my N64 controller is mapped to the Z axis. Without using BetterJoy it shows as the '4 axis 18 button joystick with hat switch' and using test is a complete mess. I've also added screenshot of the initial release for reference, which works just fine. 

Edit/ Testing on my MiSTer I can't map the C buttons, where using the Initial release I can 🤷‍♂️

With BetterJoy
![Screenshot 2023-09-25 085727](https://github.com/DavidPagels/retro-pico-switch/assets/68710299/7a592d96-7c0f-43df-a93d-2d1c4997d613)

Without BetterJoy
![Screenshot 2023-09-25 085945](https://github.com/DavidPagels/retro-pico-switch/assets/68710299/bc7e7690-f0b7-4fd8-9d09-f641d57f999b)

Initial release
![Screenshot 2023-09-25 084531](https://github.com/DavidPagels/retro-pico-switch/assets/68710299/32309f6c-4f98-4dad-8a2d-5423d0c5e7bc)

**Comment by RyanMac84** [comment]
For reference, this is how the Initial release looks using Windows 11 Game Controllers  
![Screenshot 2023-09-25 084531](https://github.com/DavidPagels/retro-pico-switch/assets/68710299/3851f299-01ea-4f27-907a-8e9e5ba29bd0)

**Comment by Sakitoshi** [comment]
you also need to change the _NonOriginalController_ value to _defaultcalibration_ in betterjoy for the stick and c-buttons to work.
![image](https://github.com/DavidPagels/retro-pico-switch/assets/39132563/8b7abf07-77c7-4a88-99e7-c2dab4cfe23a)
you can also install [hidhide](https://github.com/nefarius/HidHide/releases) and enable it (also shown in the picture above) to hide the unresponsive duplicate controller (4 axis 18 button joystick with hat switch) and prevent games from detecting it.
the Z button being detected as Z axis is normal, as the Z button is assigned as the L trigger of an xbox controller. for a more visual representation of how the system sees the controller use this web to test it: http://gamepad-tester.com.

as for MiSTer, i don't own one, but another person mentioned the same here https://github.com/DavidPagels/retro-pico-switch/issues/12#issuecomment-1731717222, you can look at the solution there.

**Comment by DavidPagels** [comment]
It looks like there may have been an issue with the usb.uf2. Resolved in #31
