### ISSUE TITLE
can't get it to connect 

### ISSUE THREAD

**Issue by annabellerinoa** [DavidPagels/retro-pico-switch#16]
Dunno why but I can't get it to connect. The only change I have is putting the original rumble motor on pin 19 and editing the cone to match. Since I don't read c++I may have gotten the code wrong. If it is the code, can you tell me the right file and line to edit and how to edit it?

**Comment by annabellerinoa** [comment]
OK. I got it to connect but still can't add the rumble feature to output to pin 19

**Comment by DavidPagels** [comment]
Since you're motivated, this project may be a good opportunity to learn C++. It was my first language, so I know it's doable. Also, this isn't necessarily a good beginner project. You may want to start by working on some simpler embedded (pico/arduino/stm32/etc) projects first.
