### ISSUE TITLE
misinputs in windows

### ISSUE THREAD

**Issue by RagGh33** [DavidPagels/retro-pico-switch#17]
I can connect the pico, flash it and windows detects it as a pro controller, but upon checking the inputs in the "Game Controller Settings" of the controller in windows, I'm getting a ton of misinputs and joystick movement is only being detected on the y-axis. this makes me think I do not have the pull up resistor installed correctly, even though I have it installed directly from the Pico's 3.3v pin intercepting on the line from the DATA pin of the N64 controller to the Pico. I've installed it in various other configurations but seem to be having no luck. Is there an Example build of how this resistor should be installed? Any help or guidance would be greatly appreciated!

**Comment by DavidPagels** [comment]
Addressed in #10
