### ISSUE TITLE
couldn't replicate results. 

### ISSUE THREAD

**Issue by c4man1111** [DavidPagels/retro-pico-switch#2]
followed instructions to a T. wired signal to GP18 and postive to 3.3v. gnd to gnd. i even took apart a n64 controller to check that everything was wired right. drag and dropped the file into the Pico (the basic one) 
not sure if i went wrong anywhere.

**Comment by DavidPagels** [comment]
Did you put a pull up resistor between 3.3v and GP18?

**Comment by c4man1111** [comment]
> 

You were right. soldered a 1k pull up resistor between GP18 and 3.3v and it worked no problem

**Comment by DavidPagels** [comment]
That's great! Glad I was able to help!
