### ISSUE TITLE
Change data pin for uf2 release 

### ISSUE THREAD

**Issue by RyanMac84** [DavidPagels/retro-pico-switch#21]
Hi, 

Rather than using a Raspberry Pi PICO, I would like to use a Seeed XIAO RP2040, however, it only has 11 I/O pins. Can you change the uf2 release to use one of the pins on the opposite side of 3v3 pin please? 

[Seeed XIAO RP2040 Pin Out](https://thepihut.com/cdn/shop/products/xiao-rp2040-seeed-104719-30512406921411_700x.jpg?v=1646067431)

Sorry it's not an issue but more of a request 🙈

**Comment by DavidPagels** [comment]
I don't do custom build sorry, you'll have to compile it yourself to change the data pin.
