### ISSUE TITLE
BlueRetro compatibility

### ISSUE THREAD

**Issue by EstudioDPP** [DavidPagels/retro-pico-switch#24]
Hello everyone! This project is an excellent idea. I would like to do it, but to use it on a real Nintendo 64 with BlueRetro already installed (via esp32 wroom with bluetooth 4.2). Do you think this very interesting project will be compatible with BlueRetro? I also have doubts that the Raspberry pi pico w is bluetooth 5.2, and the esp32 is bluetooth 4.2. 
I will greatly appreciate your response. Greetings from Argentina!

**Comment by DavidPagels** [comment]
The switch itself is Bluetooth 4.1. The protocols are the same, so it should work since it's in[ the list](https://github.com/darthcloud/BlueRetro/wiki/Controller-pairing-guide#11---list-of-tested-bluetooth-gamepads) of supported controllers.
