### ISSUE TITLE
Driver idea for Pi's with emulators 

### ISSUE THREAD

**Issue by lewilou22** [DavidPagels/retro-pico-switch#28]
Would it be possible to setup the N64 controller the same way on a Pi that has retropie installed? and use the N64 controller as a HID to play games on Pis with emulators?

Maybe a HID driver that works in a similar way

**Comment by DavidPagels** [comment]
This project requires a pi pico due to relying heavily on pio state machines for the retro controller interface. You should be able to connect that pico to the pi running retropie via usb (or bluetooth for raspberry pis >= 3) and use it the same as a pro controller, however.
