### ISSUE TITLE
can't flash firmware to original Pi Pico W

### ISSUE THREAD

**Issue by Roet-Ivar** [DavidPagels/retro-pico-switch#30]
I've now tested both bt and usb firmware on the pi pico w and it won't show up as an USB device in windows 11 at all.
Important to know is that the very first firmware gives a game controller device, so something must have happened after the release of 1.0.0.

Note: I have no soldered any connections at all at this point.

**Comment by Roet-Ivar** [comment]
@DavidPagels if I offended you in anyway I would like to apologize, I thought we really had a good conversation 4 weeks ago, but I haven't heard from you since. I hope all is well with you, health comes first!

**Comment by DavidPagels** [comment]
Resolved in #31
