### ISSUE TITLE
Example Usage of the 3D Print?

### ISSUE THREAD

**Issue by HerrTuring** [DavidPagels/retro-pico-switch#35]
I already have a working example of the project in a protoboard. But the metal pieces I used that seem to fit the N64's controller, are too big to pass that small hole in the 3D printed thing. Can you send a link to the eletronic component you use to make the 3 connections to the N64 controller that fit that square hole?

**Comment by DavidPagels** [comment]
The holes were designed to fit JST SM pins. The specific ones I used were from [this kit](https://www.amazon.com/gp/product/B07D9HRDT6/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1).
