### ISSUE TITLE
will this work on the wiiu

### ISSUE THREAD

**Issue by AceCuba** [DavidPagels/retro-pico-switch#4]
Can this be use in nindentdont on wiiu ?? like the original gamecube adaptator ?

**Comment by childofnova** [comment]
I am also curious if this can be used on a computer via USB or bluetooth? Or is this only meant to interface with the Nintendo Switch?

**Comment by DavidPagels** [comment]
It's the second listed feature at the top of the readme `Also works with any platform that supports Nintendo Switch Pro controllers`
