### ISSUE TITLE
3D Allstars with N64 Controller not working

### ISSUE THREAD

**Issue by NesTii17** [DavidPagels/retro-pico-switch#6]
The 3D Allstars Version of Super Mario 64 doesnt use the A and B Buttons to Jump and Punch.
Would be nice to Change the N64 B input to X so the Allstar Version can be Played with N64 Controller as well. 
Otherwise its not playable sadly

**Comment by DavidPagels** [comment]
There are currently no button(s) mapped to the Switch minus, capture, l3, r3, or zr buttons. The button mappings can be tweaked [here](https://github.com/DavidPagels/retro-pico-switch/blob/master/src/otherController/n64/N64Controller.cpp#L60) if you want to sacrifice another mapping though. You will have to rebuild the project to get the updated .uf2 if you go that route, however. It's awesome that you took on this project and I hope you have fun! Let me know if you have any other questions or feedback.
